import { IconType } from 'react-icons';
import { BiLogoVisualStudio } from 'react-icons/bi';
import {
  SiCloudinary,
  SiCss3,
  SiCssmodules,
  SiDrizzle,
  SiExpress,
  SiGit,
  SiGithub,
  SiGooglechrome,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMarkdown,
  SiMongodb,
  SiMongoose,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPassport,
  SiPostgresql,
  SiPostman,
  SiPuppeteer,
  SiReact,
  SiReactrouter,
  SiSass,
  SiShadcnui,
  SiSocketdotio,
  SiStyledcomponents,
  SiTailwindcss,
  SiTestinglibrary,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiZod,
} from 'react-icons/si';

export type SkillIcon = {
  icon: IconType;
  description: string;
  category: 'Frontend' | 'Backend' | 'Testing' | 'Other';
};

export const skillIcons = {
  cloudinary: {
    icon: SiCloudinary,
    description: 'Cloudinary',
    category: 'Backend',
  },
  css: { icon: SiCss3, description: 'CSS', category: 'Frontend' },
  cssModules: {
    icon: SiCssmodules,
    description: 'CSS Modules',
    category: 'Frontend',
  },
  drizzle: { icon: SiDrizzle, description: 'Drizzle', category: 'Backend' },
  express: { icon: SiExpress, description: 'Express', category: 'Backend' },
  git: { icon: SiGit, description: 'Git', category: 'Other' },
  github: { icon: SiGithub, description: 'GitHub', category: 'Other' },
  chromeDevTools: {
    icon: SiGooglechrome,
    description: 'Chrome DevTools',
    category: 'Other',
  },
  html: { icon: SiHtml5, description: 'HTML', category: 'Frontend' },
  javascript: {
    icon: SiJavascript,
    description: 'JavaScript',
    category: 'Frontend',
  },
  jest: { icon: SiJest, description: 'Jest', category: 'Testing' },
  markdown: { icon: SiMarkdown, description: 'Markdown', category: 'Other' },
  mongoDB: { icon: SiMongodb, description: 'MongoDB', category: 'Backend' },
  mongoose: { icon: SiMongoose, description: 'Mongoose', category: 'Backend' },
  netlify: { icon: SiNetlify, description: 'Netlify', category: 'Other' },
  nextJS: { icon: SiNextdotjs, description: 'Next.js', category: 'Frontend' },
  nodeJS: { icon: SiNodedotjs, description: 'Node.js', category: 'Backend' },
  npm: { icon: SiNpm, description: 'npm', category: 'Other' },
  passport: { icon: SiPassport, description: 'Passport', category: 'Backend' },
  postgresql: {
    icon: SiPostgresql,
    description: 'PostgreSQL',
    category: 'Backend',
  },
  postman: { icon: SiPostman, description: 'Postman', category: 'Testing' },
  puppeteer: {
    icon: SiPuppeteer,
    description: 'Puppeteer',
    category: 'Testing',
  },
  react: { icon: SiReact, description: 'React', category: 'Frontend' },
  reactRouter: {
    icon: SiReactrouter,
    description: 'React Router',
    category: 'Frontend',
  },
  reactTestingLibrary: {
    icon: SiTestinglibrary,
    description: 'React Testing Library',
    category: 'Testing',
  },
  tailwind: {
    icon: SiTailwindcss,
    description: 'Tailwind CSS',
    category: 'Frontend',
  },
  typescript: {
    icon: SiTypescript,
    description: 'TypeScript',
    category: 'Frontend',
  },
  sass: { icon: SiSass, description: 'Sass', category: 'Frontend' },
  shadcnui: {
    icon: SiShadcnui,
    description: 'shadcn/ui',
    category: 'Frontend',
  },
  socketIO: {
    icon: SiSocketdotio,
    description: 'Socket.IO',
    category: 'Backend',
  },
  styledComponents: {
    icon: SiStyledcomponents,
    description: 'styled-components',
    category: 'Frontend',
  },
  vercel: { icon: SiVercel, description: 'Vercel', category: 'Other' },
  vite: { icon: SiVite, description: 'Vite', category: 'Other' },
  vitest: { icon: SiVitest, description: 'Vitest', category: 'Testing' },
  vsCode: {
    icon: BiLogoVisualStudio,
    description: 'VS Code',
    category: 'Other',
  },
  zod: { icon: SiZod, description: 'Zod', category: 'Other' },
} as const satisfies Record<string, SkillIcon>;
